### ISSUE TITLE
Broken in Beta v5?

### ISSUE THREAD

**Issue by ChristopherMeyering** [andrewcbancroft/BlogIdeaList-SwiftUI#1]
Hi Mate,
Thanks for this **great** example on how to start SwiftUI!

But:
Are you able to run this code in preview currently?
Whenever I try it dies with `BlogIdeaList-SwiftUI.app crashed: communication with the app was interrupted`

Running in simulator works fine!

Kind regards,
Chris

**Comment by andrewcbancroft** [comment]
A pull request was just merged a few minutes ago that includes updates for Xcode 11 Beta 6 and iOS Beta 7.  Not sure if this clears up your issue, but you might try again?

**Comment by ChristopherMeyering** [comment]
Hi Andrew,
Strange thing. I was able to run it in simulator, but rendering the ContentView.swift in canvas still crashes.
Even in Beta 6. Very strange. But I think thats an issue at XCode itself :(

**Comment by andrewcbancroft** [comment]
I'm going to go ahead and close this issue out, now that we're past the Beta stage.  If it persists on the App Store releases of Xcode, please let me know, ok?
