### ISSUE TITLE
List doesn't update if the list order doesn't change

### ISSUE THREAD

**Issue by SchwiftyUI** [andrewcbancroft/BlogIdeaList-SwiftUI#5]
Suppose I have 3 ideas like:
ideaTitle 1: A
ideaTitle 2: B
ideaTitle 3: C

If I update the first idea's name to "Aa", the list will still show:
ideaTitle 1: A
ideaTitle 2: B
ideaTitle 3: C

Now, if i update idea 2's title to "aa" so it sorts before idea 1, the list will update to:
ideaTitle 2: aa
ideaTitle 1: Aa
ideaTitle 3: C

**Comment by PaulWoodIII** [comment]
My gut says this issue may be an issue in NSManageObject's implementation of ObservedObject. I'd wait until we have a GM to fix. We've seen this issue in multiple places in the beta.

**Comment by tclindner** [comment]
@PaulWoodIII have you had any luck with this since GM? I've been struggling with this same issue.

**Comment by PaulWoodIII** [comment]
Not really ready for a PR but checkout https://github.com/PaulWoodIII/BlogIdeaList-SwiftUI/tree/origin-master-branch

**Comment by PaulWoodIII** [comment]
The key change is noted in the commit message, we devs must call `mo.objectWillChange.send()`

**Comment by AlmightyBeaver** [comment]
In the new Xcode Version 11.2 beta (11B41) it's working... finally!

**Comment by andrewcbancroft** [comment]
I am unable to reproduce this on Xcode 11.1 + iOS 13.1 on a simulator/device.

Anyone else?

**Comment by SchwiftyUI** [comment]
Just tried this on 11.1 with your latest code, and it's working fine now. This appears to be fixed
